### ISSUE TITLE
error: Package ‘help-fns+-’ is unavailable

### ISSUE THREAD

**Issue by masai2018** [xyguo/emacs.d#10]
My OS is Win 10 and Emacs version is 26.1. I just clone all the files from your GitHub. 

Another question: when I close Emacs, it asks "save abbrevs in ~/.emacs.d/abbrevs_defs?".

Thank you very much.

**Comment by xyguo** [comment]
@masai2018 Looks like the `help-fns+` package has been removed from the ELPA repository (what's weird is that you can still find it on the EmacsWiki). The easiest way to fix this is just delete the following two lines in the file `.emacs.d/lisp/init-editing-utils.el`
```
(require-package 'help-fns+)
(require 'help-fns+)
```
Because `help-fns+` is not a essential package and you can just ignore it. Or if you do want to use this package, you can install it manually. The source code can be found [here](https://www.emacswiki.org/emacs/help-fns%2b.el).

**Comment by xyguo** [comment]
@masai2018 The "save abbrevs in ~/.emacs.d/abbrevs_defs" behavior is due to the [Abbrev Mode](https://www.emacswiki.org/emacs/AbbrevMode). It saves some user defined abbreviations locally. You can turn off this mode to prevent emacs from saving abbrevs every time.
